import Store from "@/context";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Header from "@/components/Header/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Store>
          <Header />
          {children}
        </Store>
      </body>
    </html>
  );
}
